stages:
    - build
    - doc

build dijkstra:
    stage: build
    image: alpine
    tags:
        - docker
    cache:
        paths:
            - build
    artifacts:
        paths:
            - 01Dijkstra/build/test*
    before_script:
        - apk add git python python3 gcc g++ clang make cmake boost-dev
    script:
        - mkdir -p 01Dijkstra/Release
        - cd 01Dijkstra/Release
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make
        - make test
