stages:
    - build

build dijkstra:
    stage: build
    image: alpine
    tags:
        - docker
    cache:
        paths:
            - Release
    artifacts:
        paths:
            - 01Dijkstra/Release/test*
            - 01Dijkstra/Release/time
    before_script:
        - apk add git python python3 gcc g++ clang make cmake boost-dev
    script:
        - mkdir -p 01Dijkstra/Release
        - cd 01Dijkstra/Release
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make
        - make test

build pdf:
    stage: build
    image: alpine
    tags:
        - docker
    artifacts:
        paths:
            - 01Dijkstra/tex/main.pdf
    before_script:
        - apk add make texlive-full python3 py-pip gnuplot
        - pip install pygments
    script:
        - cd 01Dijkstra/tex
        - make
    
