stages:
    - build
    - test

build dijkstra:
    stage: build
    image: alpine
    tags:
        - docker
    cache:
        paths:
            - build
    artifacts:
        paths:
            - 01Dijkstra/build/alltest
    before_script:
        - apk add git python python3 gcc g++ clang make cmake
    script:
        - mkdir -p 01Dijkstra/build
        - cd 01Dijkstra/build
        - cmake ..
        - make

test:
    stage: test
    image: alpine
    tags:
        - docker
    before_script:
        - apk add clang
    script:
        - 01Dijkstra/build/alltest
